# Generated by Django 3.2.15 on 2023-09-03 17:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='123456789', max_length=19)),
                ('last_4', models.CharField(max_length=4)),
                ('state', models.CharField(choices=[('AndraPradesh', 'AndraPradesh'), ('Telangana', 'Telangana'), ('MadhyaPradesh', 'MadhyaPradesh'), ('Delhi', 'Delhi')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='exp_year',
            field=models.PositiveSmallIntegerField(validators=[api.models.validateYear]),
        ),
    ]
