# Generated by Django 3.2.15 on 2023-09-04 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230903_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ebt_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
