# Generated by Django 3.2.15 on 2023-09-04 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_ebt_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_payments', to='api.creditcard'),
        ),
        migrations.AddField(
            model_name='payment',
            name='ebt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ebt_payments', to='api.ebt'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('ebt', 'EBT')], max_length=24),
        ),
    ]
