# Generated by Django 3.2.15 on 2023-09-04 16:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230904_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebt',
            name='issue_month',
            field=models.PositiveSmallIntegerField(default=12, validators=[api.models.validateMonth]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebt',
            name='issue_year',
            field=models.PositiveSmallIntegerField(default=12, validators=[api.models.validateYear]),
            preserve_default=False,
        ),
    ]
